### ISSUE TITLE
 KeyError: 'cpuThreads'

### ISSUE THREAD

**Issue by garugann** [Umikaze-job/All-In-LoRA#3]
Traceback (most recent call last): File "G:\All-In-LoRA\modules\Make_Lora.py", line 135, in Press_Make_Command fine_tuning_manager.make_shell_file() File "G:\All-In-LoRA\modules\class_definition\folder_manager\fine_tuning_folder_manager.py", line 207, in make_shell_file cmd = f"""accelerate launch --num_cpu_threads_per_process {self.lora_data['performance']['cpuThreads']} {self.get_train_network()} ^ KeyError: 'cpuThreads'
というエラーが出る。

**Comment by Umikaze-job** [comment]
申し訳ございません。
直します。

**Comment by Umikaze-job** [comment]
大変お待たせいたしました。
バグの修正が完了いたしました。
v1.0.0で作成したデータでv.1.0.1のAll-In-LoRAで
LoRAを作成するとバグが発生していたようです

この度は大変申し訳ございませんでした。

**Comment by Umikaze-job** [comment]
度々申し訳ございません。

やっぱり直ってないかもしれないので
もうしばらくお待ちください。

**Comment by Umikaze-job** [comment]
お待たせいたしました。
バグの件なのですが
v1.0.0で作成したデータを使って
v.1.0.1でLoRAの学習をするのが原因となっていることが発覚しましたので、
1. データをv.1.0.1で作り直す
2. 以下の画像のような状態になっているので、スライダーを動かして正常に戻す
![sa01](https://github.com/Umikaze-job/All-In-LoRA/assets/151372937/5eadfc5b-c1c3-4088-9cd2-9c6837862f1e)
このいずれかを行ってください。
